### ISSUE TITLE
Linker error in iOS when building project using Kotlin 2.0.0 and above

### ISSUE THREAD

**Issue by zeeshanali-k** [TimOrtel/GRPC-Kotlin-Multiplatform#27]
Kotlin Versions: 2.0.0 , 2.1.0 and 2.1.10

Android Studio: Android Studio Ladybug Feature Drop | 2024.2.2

grpc-multiplatform-lib: 0.4.0

Device: Mackbook M2 Pro - 16GB

Error:
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

How to regenerate:
Just create a new Kotlin Multiplatform project with or without Compose Multiplatform, and add the library setup, you should be able to see the error. Adding these pods in cocoapods block in gradle or Podfile, is the main cause of this error:
pod 'gRPC-ProtoRPC'
pod 'Protobuf'

**Comment by TimOrtel** [comment]
Could be an issue with Kotlin 2. This project has not yet been updated to Kotlin 2. Can you try and verify that this issue does not occur when you use Kotlin 1.9?

**Comment by zeeshanali-k** [comment]
Well, as the issue states that the library doesn't work with 2.*.* versions of kotlin, so it means that please add support for it. Even if I check on lower versions, it doesn't matter if it works because lower kotlin versions don't support latest xcode version. So it would be best if you can work on adding 2.0 support. Thanks.

**Comment by zeeshanali-k** [comment]
I fixed the issues by downgrading the gRPC-ProtoRPC version, for some reason latest version doesn't work with even 1.9 Kotlin version:

pod 'gRPC-ProtoRPC', '1.69.0'
